# Use an official Java runtime as a parent image
FROM openjdk:15.0.1

# Set the working directory to /app
WORKDIR /app

# Copy the app files form the host machine to image filesystem
COPY /out /app

# Set the workdirectory
 WORKDIR /app/

 # Run the main class
 CMD java Main
